// LOGGER LOGS EVERY ACTION THAT IS DISPATCHED. 
// TAKES 3 PARAMETERS - STORE, NEXT, ACTION
// STORE - REFERENCE TO THE STORE (not actually the store in log)
// NEXT - REFERENCE TO THE NEXT MIDDLEWARE FUNCTION. IF THIS IS THE ONLY
// MIDDLEWARE FUNCTION, THIS IS A REFERENCE TO THE REDUCER THAT CARRIES IT OUT 
// ACTION - ACTION THAT WAS DISPATCHED


// CURRYING - TECHNIQUE FOR CONVERTING A FUNCTION WITH END PARAMETERS
// TO A BUNCH OF FUNCTIONS EACH WITH A SINGLE PARAMETER.
// USED IN SITUATIONS WHERE WE HAVE A BUNCH OF FUNCTIONS, AND EACH
// FUNCTION SHOULD HAVE A SINGLE PARAMETER

// SNA (Store, Next, Action) - way to remember it. Sort of like DNA
const logger = param => store => next => action => {
    console.log("Logging", param);
    return next(action);
}

export default logger;